items:
- uid: System.IO.EndOfStreamException
  id: EndOfStreamException
  parent: System.IO
  children:
  - System.IO.EndOfStreamException.#ctor
  - System.IO.EndOfStreamException.#ctor(System.String)
  - System.IO.EndOfStreamException.#ctor(System.String,System.Exception)
  name: EndOfStreamException
  fullName: System.IO.EndOfStreamException
  type: Class
  source:
    remote: &o0
      path: src/mscorlib/src/System/IO/EndOfStreamException.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    path: src/mscorlib/src/System/IO/EndOfStreamException.cs
    startLine: 19
  assemblies:
  - System.IO
  namespace: System.IO
  summary: The exception that is thrown when reading is attempted past the end of a stream.
  syntax:
    content: 'public class EndOfStreamException : IOException'
    content.vb: Public Class EndOfStreamException Inherits IOException
  inheritance:
  - System.Object
- uid: System.IO.EndOfStreamException.#ctor
  id: '#ctor'
  parent: System.IO.EndOfStreamException
  name: EndOfStreamException()
  fullName: System.IO.EndOfStreamException.EndOfStreamException()
  type: Constructor
  source:
    remote: *o0
    path: src/mscorlib/src/System/IO/EndOfStreamException.cs
    startLine: 23
  assemblies:
  - System.IO
  namespace: System.IO
  summary: Initializes a new instance of the <xref href="System.IO.EndOfStreamException" data-throw-if-not-resolved="false"></xref> class with its message string set to a system-supplied message and its HRESULT set to COR_E_ENDOFSTREAM.
  syntax:
    content: public EndOfStreamException()
    content.vb: Public Sub New
- uid: System.IO.EndOfStreamException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.IO.EndOfStreamException
  name: EndOfStreamException(String)
  fullName: System.IO.EndOfStreamException.EndOfStreamException(System.String)
  type: Constructor
  source:
    remote: *o0
    path: src/mscorlib/src/System/IO/EndOfStreamException.cs
    startLine: 28
  assemblies:
  - System.IO
  namespace: System.IO
  summary: Initializes a new instance of the <xref href="System.IO.EndOfStreamException" data-throw-if-not-resolved="false"></xref> class with its message string set to *message* and its HRESULT set to COR_E_ENDOFSTREAM.
  syntax:
    content: public EndOfStreamException(string message)
    content.vb: Public Sub New(message As String)
    parameters:
    - id: message
      type: System.String
      description: A string that describes the error. The content of *message* is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.
- uid: System.IO.EndOfStreamException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.IO.EndOfStreamException
  name: EndOfStreamException(String, Exception)
  fullName: System.IO.EndOfStreamException.EndOfStreamException(System.String, System.Exception)
  type: Constructor
  source:
    remote: *o0
    path: src/mscorlib/src/System/IO/EndOfStreamException.cs
    startLine: 33
  assemblies:
  - System.IO
  namespace: System.IO
  summary: Initializes a new instance of the <xref href="System.IO.EndOfStreamException" data-throw-if-not-resolved="false"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.
  syntax:
    content: public EndOfStreamException(string message, Exception innerException)
    content.vb: Public Sub New(message As String, innerException As Exception)
    parameters:
    - id: message
      type: System.String
      description: A string that describes the error. The content of *message* is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.
    - id: innerException
      type: System.Exception
      description: The exception that is the cause of the current exception. If the *innerException* parameter is not null, the current exception is raised in a catch block that handles the inner exception.
references:
- uid: System.IO
  isExternal: false
  name: System.IO
  fullName: System.IO
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.String
  parent: System
  isExternal: false
  name: String
  fullName: System.String
- uid: System.Exception
  parent: System
  isExternal: false
  name: Exception
  fullName: System.Exception
